project:
  type: website

website:
  title: "UPWINS"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: about.ipynb
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



