project:
  type: website

website:
  title: "UPWINS"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: reports.ipynb
        text: Reports
      - href: about.ipynb
        text: About
  sidebar:
    - title: Reports
      style: floating
      contents:
        - reports.ipynb
        - reports/SaltReport.ipynb
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



